title: Lorenzo Poggioni
logo: /assets/profile.jpg
description: >
  PhD Student in Applied Mathematics <br>
  <a href="https://www.linkedin.com/in/lorenzo-poggioni-a326763a2/">LinkedIn</a> | 
  <a href="mailto:lorenzo.poggioni@proton.me">Email</a>

theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0